version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/base:2023.10
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true  # Habilita la caché de capas de Docker
      - run:
          name: Construir imagen de Docker
          command: |
            docker build -t $DOCKER_USERNAME/vvflask:latest .
      - run:
          name: Autenticar con Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Subir imagen a Docker Hub
          command: |
            docker push $DOCKER_USERNAME/vvflask:latest

  deploy_with_ansible:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Instalar Ansible
          command: |
            pip install ansible
      - add_ssh_keys:
          fingerprints:
            - "${SSH_KEY_FINGERPRINT}"
      - run:
          name: Configurar known_hosts
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H $VPS_IP >> ~/.ssh/known_hosts
      - run:
          name: Instalar sshpass
          command: sudo apt-get update && sudo apt-get install -y sshpass

      - run:
          name: Ejecutar playbook de Ansible
          command: |
            sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP \
            'cd /home/sylvana/ansibles/ && ansible-playbook -i inventory.ini playbook.yml'

workflows:
  version: 2
  build_deploy_and_run:
    jobs:
      - build_and_push:
          filters:
            branches:
              only: main
      - deploy_with_ansible:
          requires:
            - build_and_push
          filters:
            branches:
              only: main
