version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/base:2023.10
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Instalar Docker cliente
          command: |
            set -x
            VER="20.10.9"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin
      - run:
          name: Construir imagen de Docker
          command: |
            docker build -t $DOCKER_USERNAME/vvflask:latest .
      - run:
          name: Autenticar con Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Subir imagen a Docker Hub
          command: |
            docker push $DOCKER_USERNAME/vvflask:latest

  deploy_with_ansible:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Instalar Ansible
          command: |
            pip install ansible
      - add_ssh_keys:
          fingerprints:
            - "${SSH_KEY_FINGERPRINT}"  # Necesitarás configurar esto en CircleCI
      - run:
          name: Configurar known_hosts
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H $VPS_IP >> ~/.ssh/known_hosts
      - run:
          name: Ejecutar playbook de Ansible
          command: |
            ssh $VPS_USER@$VPS_IP "cd /home/sylvana/ansibles/ && ansible-playbook -i inventory.ini playbook.yml"

workflows:
  version: 2
  build_deploy_and_run:
    jobs:
      - build_and_push:
          filters:
            branches:
              only: main
      - deploy_with_ansible:
          requires:
            - build_and_push
          filters:
            branches:
              only: main




